#External Prior/Transform Input
extrinsics:
  worldFrame: world
  odomFrame: odom
  imuFrame: imu     #imu  #Frame of IMU used in integrator - Used for lookup transform to lidarFrame
  baseLinkFrame: atnj1
  initializeZeroYawAndPositionOfFrame: atnj1
