# Sensor Params
sensor_params:
  positionRate: 20 # Rate of the Position input (Hz)

# Noise Parameters
noise_params:
  ## Position measurement
  PositionMeasUnaryNoise: 0.04 # x, y, z of global position
  RealsenseOdomPoseUnaryNoise: [ 0.25, 0.25, 0.25, 0.05, 0.05, 0.05 ] # ORDER RPY(rad) - XYZ(meters)