# Sensor Params
sensor_params:
  positionRate: 20 # Rate of the GNSS

# Noise Parameters
noise_params:
  ## LiDAR
  lioPoseUnaryNoise: [ 0.25, 0.25, 0.25, 0.05, 0.05, 0.05 ] # ORDER RPY(rad) - XYZ(meters)
  ## GNSS
  gnssPositionUnaryNoise: 0.04 # x, y, z of global position
  gnssHeadingUnaryNoise: 0.2   # radians